// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryClient creates a new instance of MockRegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryClient {
	mock := &MockRegistryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryClient is an autogenerated mock type for the RegistryClient type
type MockRegistryClient struct {
	mock.Mock
}

type MockRegistryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryClient) EXPECT() *MockRegistryClient_Expecter {
	return &MockRegistryClient_Expecter{mock: &_m.Mock}
}

// GetRegistryAuth provides a mock function for the type MockRegistryClient
func (_mock *MockRegistryClient) GetRegistryAuth(imageRef string) string {
	ret := _mock.Called(imageRef)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryAuth")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(imageRef)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRegistryClient_GetRegistryAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryAuth'
type MockRegistryClient_GetRegistryAuth_Call struct {
	*mock.Call
}

// GetRegistryAuth is a helper method to define mock.On call
//   - imageRef string
func (_e *MockRegistryClient_Expecter) GetRegistryAuth(imageRef interface{}) *MockRegistryClient_GetRegistryAuth_Call {
	return &MockRegistryClient_GetRegistryAuth_Call{Call: _e.mock.On("GetRegistryAuth", imageRef)}
}

func (_c *MockRegistryClient_GetRegistryAuth_Call) Run(run func(imageRef string)) *MockRegistryClient_GetRegistryAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistryClient_GetRegistryAuth_Call) Return(s string) *MockRegistryClient_GetRegistryAuth_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRegistryClient_GetRegistryAuth_Call) RunAndReturn(run func(imageRef string) string) *MockRegistryClient_GetRegistryAuth_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoteDigest provides a mock function for the type MockRegistryClient
func (_mock *MockRegistryClient) GetRemoteDigest(ctx context.Context, imageRef string) (string, error) {
	ret := _mock.Called(ctx, imageRef)

	if len(ret) == 0 {
		panic("no return value specified for GetRemoteDigest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, imageRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, imageRef)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, imageRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryClient_GetRemoteDigest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoteDigest'
type MockRegistryClient_GetRemoteDigest_Call struct {
	*mock.Call
}

// GetRemoteDigest is a helper method to define mock.On call
//   - ctx context.Context
//   - imageRef string
func (_e *MockRegistryClient_Expecter) GetRemoteDigest(ctx interface{}, imageRef interface{}) *MockRegistryClient_GetRemoteDigest_Call {
	return &MockRegistryClient_GetRemoteDigest_Call{Call: _e.mock.On("GetRemoteDigest", ctx, imageRef)}
}

func (_c *MockRegistryClient_GetRemoteDigest_Call) Run(run func(ctx context.Context, imageRef string)) *MockRegistryClient_GetRemoteDigest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistryClient_GetRemoteDigest_Call) Return(s string, err error) *MockRegistryClient_GetRemoteDigest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRegistryClient_GetRemoteDigest_Call) RunAndReturn(run func(ctx context.Context, imageRef string) (string, error)) *MockRegistryClient_GetRemoteDigest_Call {
	_c.Call.Return(run)
	return _c
}

// HasNewImage provides a mock function for the type MockRegistryClient
func (_mock *MockRegistryClient) HasNewImage(ctx context.Context, imageRef string, localDigest string) (bool, string, error) {
	ret := _mock.Called(ctx, imageRef, localDigest)

	if len(ret) == 0 {
		panic("no return value specified for HasNewImage")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, string, error)); ok {
		return returnFunc(ctx, imageRef, localDigest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, imageRef, localDigest)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, imageRef, localDigest)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, imageRef, localDigest)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRegistryClient_HasNewImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNewImage'
type MockRegistryClient_HasNewImage_Call struct {
	*mock.Call
}

// HasNewImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageRef string
//   - localDigest string
func (_e *MockRegistryClient_Expecter) HasNewImage(ctx interface{}, imageRef interface{}, localDigest interface{}) *MockRegistryClient_HasNewImage_Call {
	return &MockRegistryClient_HasNewImage_Call{Call: _e.mock.On("HasNewImage", ctx, imageRef, localDigest)}
}

func (_c *MockRegistryClient_HasNewImage_Call) Run(run func(ctx context.Context, imageRef string, localDigest string)) *MockRegistryClient_HasNewImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRegistryClient_HasNewImage_Call) Return(b bool, s string, err error) *MockRegistryClient_HasNewImage_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockRegistryClient_HasNewImage_Call) RunAndReturn(run func(ctx context.Context, imageRef string, localDigest string) (bool, string, error)) *MockRegistryClient_HasNewImage_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type MockRegistryClient
func (_mock *MockRegistryClient) ListTags(ctx context.Context, imageRef string) ([]string, error) {
	ret := _mock.Called(ctx, imageRef)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, imageRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, imageRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, imageRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryClient_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockRegistryClient_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - imageRef string
func (_e *MockRegistryClient_Expecter) ListTags(ctx interface{}, imageRef interface{}) *MockRegistryClient_ListTags_Call {
	return &MockRegistryClient_ListTags_Call{Call: _e.mock.On("ListTags", ctx, imageRef)}
}

func (_c *MockRegistryClient_ListTags_Call) Run(run func(ctx context.Context, imageRef string)) *MockRegistryClient_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistryClient_ListTags_Call) Return(strings []string, err error) *MockRegistryClient_ListTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRegistryClient_ListTags_Call) RunAndReturn(run func(ctx context.Context, imageRef string) ([]string, error)) *MockRegistryClient_ListTags_Call {
	_c.Call.Return(run)
	return _c
}
