// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/huseyinbabal/updock/internal/docker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerClient creates a new instance of MockDockerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerClient {
	mock := &MockDockerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerClient is an autogenerated mock type for the DockerClient type
type MockDockerClient struct {
	mock.Mock
}

type MockDockerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerClient) EXPECT() *MockDockerClient_Expecter {
	return &MockDockerClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDockerClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDockerClient_Expecter) Close() *MockDockerClient_Close_Call {
	return &MockDockerClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDockerClient_Close_Call) Run(run func()) *MockDockerClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerClient_Close_Call) Return(err error) *MockDockerClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_Close_Call) RunAndReturn(run func() error) *MockDockerClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecCommand provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) ExecCommand(ctx context.Context, containerID string, cmd string, timeout time.Duration) (string, error) {
	ret := _mock.Called(ctx, containerID, cmd, timeout)

	if len(ret) == 0 {
		panic("no return value specified for ExecCommand")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, containerID, cmd, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, containerID, cmd, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, containerID, cmd, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_ExecCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecCommand'
type MockDockerClient_ExecCommand_Call struct {
	*mock.Call
}

// ExecCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - cmd string
//   - timeout time.Duration
func (_e *MockDockerClient_Expecter) ExecCommand(ctx interface{}, containerID interface{}, cmd interface{}, timeout interface{}) *MockDockerClient_ExecCommand_Call {
	return &MockDockerClient_ExecCommand_Call{Call: _e.mock.On("ExecCommand", ctx, containerID, cmd, timeout)}
}

func (_c *MockDockerClient_ExecCommand_Call) Run(run func(ctx context.Context, containerID string, cmd string, timeout time.Duration)) *MockDockerClient_ExecCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDockerClient_ExecCommand_Call) Return(s string, err error) *MockDockerClient_ExecCommand_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDockerClient_ExecCommand_Call) RunAndReturn(run func(ctx context.Context, containerID string, cmd string, timeout time.Duration) (string, error)) *MockDockerClient_ExecCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependencies provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) GetDependencies(ctx context.Context, containerID string) ([]string, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencies")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_GetDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependencies'
type MockDockerClient_GetDependencies_Call struct {
	*mock.Call
}

// GetDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockDockerClient_Expecter) GetDependencies(ctx interface{}, containerID interface{}) *MockDockerClient_GetDependencies_Call {
	return &MockDockerClient_GetDependencies_Call{Call: _e.mock.On("GetDependencies", ctx, containerID)}
}

func (_c *MockDockerClient_GetDependencies_Call) Run(run func(ctx context.Context, containerID string)) *MockDockerClient_GetDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerClient_GetDependencies_Call) Return(strings []string, err error) *MockDockerClient_GetDependencies_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDockerClient_GetDependencies_Call) RunAndReturn(run func(ctx context.Context, containerID string) ([]string, error)) *MockDockerClient_GetDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageDigest provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) GetImageDigest(ctx context.Context, imageID string) (string, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for GetImageDigest")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_GetImageDigest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageDigest'
type MockDockerClient_GetImageDigest_Call struct {
	*mock.Call
}

// GetImageDigest is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockDockerClient_Expecter) GetImageDigest(ctx interface{}, imageID interface{}) *MockDockerClient_GetImageDigest_Call {
	return &MockDockerClient_GetImageDigest_Call{Call: _e.mock.On("GetImageDigest", ctx, imageID)}
}

func (_c *MockDockerClient_GetImageDigest_Call) Run(run func(ctx context.Context, imageID string)) *MockDockerClient_GetImageDigest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerClient_GetImageDigest_Call) Return(s string, err error) *MockDockerClient_GetImageDigest_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDockerClient_GetImageDigest_Call) RunAndReturn(run func(ctx context.Context, imageID string) (string, error)) *MockDockerClient_GetImageDigest_Call {
	_c.Call.Return(run)
	return _c
}

// InspectContainer provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) InspectContainer(ctx context.Context, id string) (*docker.ContainerInfo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for InspectContainer")
	}

	var r0 *docker.ContainerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*docker.ContainerInfo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *docker.ContainerInfo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*docker.ContainerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_InspectContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectContainer'
type MockDockerClient_InspectContainer_Call struct {
	*mock.Call
}

// InspectContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDockerClient_Expecter) InspectContainer(ctx interface{}, id interface{}) *MockDockerClient_InspectContainer_Call {
	return &MockDockerClient_InspectContainer_Call{Call: _e.mock.On("InspectContainer", ctx, id)}
}

func (_c *MockDockerClient_InspectContainer_Call) Run(run func(ctx context.Context, id string)) *MockDockerClient_InspectContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerClient_InspectContainer_Call) Return(containerInfo *docker.ContainerInfo, err error) *MockDockerClient_InspectContainer_Call {
	_c.Call.Return(containerInfo, err)
	return _c
}

func (_c *MockDockerClient_InspectContainer_Call) RunAndReturn(run func(ctx context.Context, id string) (*docker.ContainerInfo, error)) *MockDockerClient_InspectContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) ListContainers(ctx context.Context, includeStopped bool, includeRestarting bool) ([]docker.ContainerInfo, error) {
	ret := _mock.Called(ctx, includeStopped, includeRestarting)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 []docker.ContainerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, bool) ([]docker.ContainerInfo, error)); ok {
		return returnFunc(ctx, includeStopped, includeRestarting)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, bool) []docker.ContainerInfo); ok {
		r0 = returnFunc(ctx, includeStopped, includeRestarting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]docker.ContainerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, bool) error); ok {
		r1 = returnFunc(ctx, includeStopped, includeRestarting)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockDockerClient_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - includeStopped bool
//   - includeRestarting bool
func (_e *MockDockerClient_Expecter) ListContainers(ctx interface{}, includeStopped interface{}, includeRestarting interface{}) *MockDockerClient_ListContainers_Call {
	return &MockDockerClient_ListContainers_Call{Call: _e.mock.On("ListContainers", ctx, includeStopped, includeRestarting)}
}

func (_c *MockDockerClient_ListContainers_Call) Run(run func(ctx context.Context, includeStopped bool, includeRestarting bool)) *MockDockerClient_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDockerClient_ListContainers_Call) Return(containerInfos []docker.ContainerInfo, err error) *MockDockerClient_ListContainers_Call {
	_c.Call.Return(containerInfos, err)
	return _c
}

func (_c *MockDockerClient_ListContainers_Call) RunAndReturn(run func(ctx context.Context, includeStopped bool, includeRestarting bool) ([]docker.ContainerInfo, error)) *MockDockerClient_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDockerClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDockerClient_Expecter) Ping(ctx interface{}) *MockDockerClient_Ping_Call {
	return &MockDockerClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDockerClient_Ping_Call) Run(run func(ctx context.Context)) *MockDockerClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDockerClient_Ping_Call) Return(err error) *MockDockerClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockDockerClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PullImage provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) PullImage(ctx context.Context, ref string, registryAuth string) (string, error) {
	ret := _mock.Called(ctx, ref, registryAuth)

	if len(ret) == 0 {
		panic("no return value specified for PullImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, ref, registryAuth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, ref, registryAuth)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ref, registryAuth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_PullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullImage'
type MockDockerClient_PullImage_Call struct {
	*mock.Call
}

// PullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - registryAuth string
func (_e *MockDockerClient_Expecter) PullImage(ctx interface{}, ref interface{}, registryAuth interface{}) *MockDockerClient_PullImage_Call {
	return &MockDockerClient_PullImage_Call{Call: _e.mock.On("PullImage", ctx, ref, registryAuth)}
}

func (_c *MockDockerClient_PullImage_Call) Run(run func(ctx context.Context, ref string, registryAuth string)) *MockDockerClient_PullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDockerClient_PullImage_Call) Return(s string, err error) *MockDockerClient_PullImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDockerClient_PullImage_Call) RunAndReturn(run func(ctx context.Context, ref string, registryAuth string) (string, error)) *MockDockerClient_PullImage_Call {
	_c.Call.Return(run)
	return _c
}

// RecreateContainer provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) RecreateContainer(ctx context.Context, id string, newImage string, stopTimeout time.Duration, customSignal string, removeVolumes bool) (string, error) {
	ret := _mock.Called(ctx, id, newImage, stopTimeout, customSignal, removeVolumes)

	if len(ret) == 0 {
		panic("no return value specified for RecreateContainer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration, string, bool) (string, error)); ok {
		return returnFunc(ctx, id, newImage, stopTimeout, customSignal, removeVolumes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration, string, bool) string); ok {
		r0 = returnFunc(ctx, id, newImage, stopTimeout, customSignal, removeVolumes)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration, string, bool) error); ok {
		r1 = returnFunc(ctx, id, newImage, stopTimeout, customSignal, removeVolumes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerClient_RecreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecreateContainer'
type MockDockerClient_RecreateContainer_Call struct {
	*mock.Call
}

// RecreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newImage string
//   - stopTimeout time.Duration
//   - customSignal string
//   - removeVolumes bool
func (_e *MockDockerClient_Expecter) RecreateContainer(ctx interface{}, id interface{}, newImage interface{}, stopTimeout interface{}, customSignal interface{}, removeVolumes interface{}) *MockDockerClient_RecreateContainer_Call {
	return &MockDockerClient_RecreateContainer_Call{Call: _e.mock.On("RecreateContainer", ctx, id, newImage, stopTimeout, customSignal, removeVolumes)}
}

func (_c *MockDockerClient_RecreateContainer_Call) Run(run func(ctx context.Context, id string, newImage string, stopTimeout time.Duration, customSignal string, removeVolumes bool)) *MockDockerClient_RecreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDockerClient_RecreateContainer_Call) Return(s string, err error) *MockDockerClient_RecreateContainer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDockerClient_RecreateContainer_Call) RunAndReturn(run func(ctx context.Context, id string, newImage string, stopTimeout time.Duration, customSignal string, removeVolumes bool) (string, error)) *MockDockerClient_RecreateContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveContainer provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) RemoveContainer(ctx context.Context, id string, removeVolumes bool) error {
	ret := _mock.Called(ctx, id, removeVolumes)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, removeVolumes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockDockerClient_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - removeVolumes bool
func (_e *MockDockerClient_Expecter) RemoveContainer(ctx interface{}, id interface{}, removeVolumes interface{}) *MockDockerClient_RemoveContainer_Call {
	return &MockDockerClient_RemoveContainer_Call{Call: _e.mock.On("RemoveContainer", ctx, id, removeVolumes)}
}

func (_c *MockDockerClient_RemoveContainer_Call) Run(run func(ctx context.Context, id string, removeVolumes bool)) *MockDockerClient_RemoveContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDockerClient_RemoveContainer_Call) Return(err error) *MockDockerClient_RemoveContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_RemoveContainer_Call) RunAndReturn(run func(ctx context.Context, id string, removeVolumes bool) error) *MockDockerClient_RemoveContainer_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveImage provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) RemoveImage(ctx context.Context, imageID string) error {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_RemoveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveImage'
type MockDockerClient_RemoveImage_Call struct {
	*mock.Call
}

// RemoveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockDockerClient_Expecter) RemoveImage(ctx interface{}, imageID interface{}) *MockDockerClient_RemoveImage_Call {
	return &MockDockerClient_RemoveImage_Call{Call: _e.mock.On("RemoveImage", ctx, imageID)}
}

func (_c *MockDockerClient_RemoveImage_Call) Run(run func(ctx context.Context, imageID string)) *MockDockerClient_RemoveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerClient_RemoveImage_Call) Return(err error) *MockDockerClient_RemoveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_RemoveImage_Call) RunAndReturn(run func(ctx context.Context, imageID string) error) *MockDockerClient_RemoveImage_Call {
	_c.Call.Return(run)
	return _c
}

// StartContainer provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) StartContainer(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for StartContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockDockerClient_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDockerClient_Expecter) StartContainer(ctx interface{}, id interface{}) *MockDockerClient_StartContainer_Call {
	return &MockDockerClient_StartContainer_Call{Call: _e.mock.On("StartContainer", ctx, id)}
}

func (_c *MockDockerClient_StartContainer_Call) Run(run func(ctx context.Context, id string)) *MockDockerClient_StartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerClient_StartContainer_Call) Return(err error) *MockDockerClient_StartContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_StartContainer_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDockerClient_StartContainer_Call {
	_c.Call.Return(run)
	return _c
}

// StopContainer provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) StopContainer(ctx context.Context, id string, timeout time.Duration, customSignal string) error {
	ret := _mock.Called(ctx, id, timeout, customSignal)

	if len(ret) == 0 {
		panic("no return value specified for StopContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string) error); ok {
		r0 = returnFunc(ctx, id, timeout, customSignal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockDockerClient_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - timeout time.Duration
//   - customSignal string
func (_e *MockDockerClient_Expecter) StopContainer(ctx interface{}, id interface{}, timeout interface{}, customSignal interface{}) *MockDockerClient_StopContainer_Call {
	return &MockDockerClient_StopContainer_Call{Call: _e.mock.On("StopContainer", ctx, id, timeout, customSignal)}
}

func (_c *MockDockerClient_StopContainer_Call) Run(run func(ctx context.Context, id string, timeout time.Duration, customSignal string)) *MockDockerClient_StopContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDockerClient_StopContainer_Call) Return(err error) *MockDockerClient_StopContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_StopContainer_Call) RunAndReturn(run func(ctx context.Context, id string, timeout time.Duration, customSignal string) error) *MockDockerClient_StopContainer_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForHealthy provides a mock function for the type MockDockerClient
func (_mock *MockDockerClient) WaitForHealthy(ctx context.Context, containerID string, timeout time.Duration) error {
	ret := _mock.Called(ctx, containerID, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForHealthy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, containerID, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerClient_WaitForHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForHealthy'
type MockDockerClient_WaitForHealthy_Call struct {
	*mock.Call
}

// WaitForHealthy is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
//   - timeout time.Duration
func (_e *MockDockerClient_Expecter) WaitForHealthy(ctx interface{}, containerID interface{}, timeout interface{}) *MockDockerClient_WaitForHealthy_Call {
	return &MockDockerClient_WaitForHealthy_Call{Call: _e.mock.On("WaitForHealthy", ctx, containerID, timeout)}
}

func (_c *MockDockerClient_WaitForHealthy_Call) Run(run func(ctx context.Context, containerID string, timeout time.Duration)) *MockDockerClient_WaitForHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDockerClient_WaitForHealthy_Call) Return(err error) *MockDockerClient_WaitForHealthy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerClient_WaitForHealthy_Call) RunAndReturn(run func(ctx context.Context, containerID string, timeout time.Duration) error) *MockDockerClient_WaitForHealthy_Call {
	_c.Call.Return(run)
	return _c
}
